version: "3.8"

services:
    go:
        build: ./src
        ports:
            - "8087:8080"
        container_name: go
        volumes:
            - ./src:/src
        tty: true
        # command: go run main.go

    db:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sample
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            TZ: "Asia/Tokyo"
        volumes:
            - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
            - 3306:3306
